#ifndef _LIBDLSP_UNDERLAY_H_
#define _LIBDLSP_UNDERLAY_H_

// STDIO
#define UNDERLAY_FIXED_PRINTF_NTSC              (0x0011D5D8)
#define UNDERLAY_FIXED_SPRINTF_NTSC             (0x0011D920)
#define UNDERLAY_FIXED_SNPRINTF_NTSC            (0x0011D878)
#define UNDERLAY_FIXED_SSCANF_NTSC              (0x0011D9A8)
#define UNDERLAY_FIXED_MEMSET_NTSC              (0x0011A518)
#define UNDERLAY_FIXED_MEMCPY_NTSC              (0x0011A370)
#define UNDERLAY_FIXED_MEMMOVE_NTSC             (0x0011A41C)
#define UNDERLAY_FIXED_MEMCMP_NTSC              (0x0011A2DC)
#define UNDERLAY_FIXED_STRNCPY_NTSC             (0x0011AFC8)
#define UNDERLAY_FIXED_STRLEN_NTSC              (0x0011AB04)
#define UNDERLAY_FIXED_STRCMP_NTSC              (0x0011A8A0)
#define UNDERLAY_FIXED_STRSTR_NTSC              (0x00122160)
#define UNDERLAY_FIXED_MALLOC_NTSC              (0x0011ef60)
#define UNDERLAY_FIXED_FREE_NTSC                (0x0011efb0)

// MATH
#define UNDERLAY_FIXED_ASINF_NTSC               (0x00136278)
#define UNDERLAY_FIXED_POWF_NTSC                (0x00136788)
#define UNDERLAY_FIXED_FABSF_NTSC               (0x00135960)
#define UNDERLAY_FIXED_FPTODP_NTSC              (0x00131918)
#define UNDERLAY_FIXED_FLOORF_NTSC              (0x001359A8)
#define UNDERLAY_FIXED_DIVDI3_NTSC              (0x0012feb0)
#define UNDERLAY_FIXED_CEILF_NTSC               (0x00135770)
#define UNDERLAY_FIXED_LOGF_NTSC                (0x001364f0)
#define UNDERLAY_FIXED_LOG10F_NTSC              (0x00136638)

// MISC
#define UNDERLAY_GAME_LEVEL_NTSC                (0x00172160 + 0x198)

#if NTSC

#define UNDERLAY_FIXED_PRINTF UNDERLAY_FIXED_PRINTF_NTSC
#define UNDERLAY_FIXED_SPRINTF UNDERLAY_FIXED_SPRINTF_NTSC
#define UNDERLAY_FIXED_SNPRINTF UNDERLAY_FIXED_SNPRINTF_NTSC
#define UNDERLAY_FIXED_SSCANF UNDERLAY_FIXED_SSCANF_NTSC
#define UNDERLAY_FIXED_MEMSET UNDERLAY_FIXED_MEMSET_NTSC
#define UNDERLAY_FIXED_MEMCPY UNDERLAY_FIXED_MEMCPY_NTSC
#define UNDERLAY_FIXED_MEMMOVE UNDERLAY_FIXED_MEMMOVE_NTSC
#define UNDERLAY_FIXED_MEMCMP UNDERLAY_FIXED_MEMCMP_NTSC
#define UNDERLAY_FIXED_STRNCPY UNDERLAY_FIXED_STRNCPY_NTSC
#define UNDERLAY_FIXED_STRLEN UNDERLAY_FIXED_STRLEN_NTSC
#define UNDERLAY_FIXED_STRCMP UNDERLAY_FIXED_STRCMP_NTSC
#define UNDERLAY_FIXED_STRSTR UNDERLAY_FIXED_STRSTR_NTSC
#define UNDERLAY_FIXED_MALLOC UNDERLAY_FIXED_MALLOC_NTSC
#define UNDERLAY_FIXED_FREE UNDERLAY_FIXED_FREE_NTSC

#define UNDERLAY_FIXED_ASINF UNDERLAY_FIXED_ASINF_NTSC
#define UNDERLAY_FIXED_POWF UNDERLAY_FIXED_POWF_NTSC
#define UNDERLAY_FIXED_FABSF UNDERLAY_FIXED_FABSF_NTSC
#define UNDERLAY_FIXED_FPTODP UNDERLAY_FIXED_FPTODP_NTSC
#define UNDERLAY_FIXED_FLOORF UNDERLAY_FIXED_FLOORF_NTSC
#define UNDERLAY_FIXED_DIVDI3 UNDERLAY_FIXED_DIVDI3_NTSC
#define UNDERLAY_FIXED_CEILF UNDERLAY_FIXED_CEILF_NTSC
#define UNDERLAY_FIXED_LOGF UNDERLAY_FIXED_LOGF_NTSC
#define UNDERLAY_FIXED_LOG10F UNDERLAY_FIXED_LOG10F_NTSC

#define UNDERLAY_GAME_LEVEL UNDERLAY_GAME_LEVEL_NTSC

#elif PAL

#endif


#endif // _LIBDLSP_UNDERLAY_H_
