#include "underlay.h"
#include "overlay.h"
#include "helpers.h"
#include "enums.h"
#include "pad.h"
#include "font.h"

// map level id to overlay lookup index
// all multiplayer levels have the same overlay
// matching singleplayer and coop levels share the same overlay
// all invalid levels default to -1
char LevelToLookupIndexId[LEVEL_ID_COUNT] = {
  [LEVEL_ID_MAIN_MENU] OVERLAY_LOOKUP_MAIN_MENU,
  [LEVEL_ID_BATTLEDOME] OVERLAY_LOOKUP_BATTLEDOME,
  [LEVEL_ID_CATACROM] OVERLAY_LOOKUP_CATACROM,
  [3] = -1,
  [LEVEL_ID_SARATHOS] OVERLAY_LOOKUP_SARATHOS,
  [LEVEL_ID_KRONOS] OVERLAY_LOOKUP_KRONOS,
  [LEVEL_ID_SHAAR] OVERLAY_LOOKUP_SHAAR,
  [LEVEL_ID_ORXON] OVERLAY_LOOKUP_ORXON,
  [LEVEL_ID_VALIX] OVERLAY_LOOKUP_VALIX,
  [9] = -1,
  [LEVEL_ID_TORVAL] OVERLAY_LOOKUP_TORVAL,
  [LEVEL_ID_STYGIA] OVERLAY_LOOKUP_STYGIA,
  [12] = -1,
  [LEVEL_ID_MARAXUS] OVERLAY_LOOKUP_MARAXUS,
  [LEVEL_ID_GHOST_STATION] OVERLAY_LOOKUP_GHOST_STATION,
  [LEVEL_ID_CONTROL_LEVEL] OVERLAY_LOOKUP_CONTROL_LEVEL,
  [16] = -1,
  [17] = -1,
  [18] = -1,
  [19] = -1,
  [20] = -1,
  [LEVEL_ID_COOP_BATTLEDOME] OVERLAY_LOOKUP_BATTLEDOME,
  [LEVEL_ID_COOP_CATACROM] OVERLAY_LOOKUP_CATACROM,
  [23] = -1,
  [LEVEL_ID_COOP_SARATHOS] OVERLAY_LOOKUP_SARATHOS,
  [LEVEL_ID_COOP_KRONOS] OVERLAY_LOOKUP_KRONOS,
  [LEVEL_ID_COOP_SHAAR] OVERLAY_LOOKUP_SHAAR,
  [LEVEL_ID_COOP_ORXON] OVERLAY_LOOKUP_ORXON,
  [LEVEL_ID_COOP_VALIX] OVERLAY_LOOKUP_VALIX,
  [29] = -1,
  [LEVEL_ID_COOP_TORVAL] OVERLAY_LOOKUP_TORVAL,
  [LEVEL_ID_COOP_STYGIA] OVERLAY_LOOKUP_STYGIA,
  [32] = -1,
  [LEVEL_ID_COOP_MARAXUS] OVERLAY_LOOKUP_MARAXUS,
  [LEVEL_ID_COOP_GHOST_STATION] OVERLAY_LOOKUP_GHOST_STATION,
  [LEVEL_ID_COOP_CONTROL_LEVEL] OVERLAY_LOOKUP_CONTROL_LEVEL,
  [36] = -1,
  [37] = -1,
  [38] = -1,
  [39] = -1,
  [40] = -1,
  [LEVEL_ID_MP_BATTLEDOME] OVERLAY_LOOKUP_MP_INGAME,
  [LEVEL_ID_MP_CATACROM] OVERLAY_LOOKUP_MP_INGAME,
  [42] = -1,
  [LEVEL_ID_MP_SARATHOS] OVERLAY_LOOKUP_MP_INGAME,
  [LEVEL_ID_MP_KRONOS] OVERLAY_LOOKUP_MP_INGAME,
  [LEVEL_ID_MP_SHAAR] OVERLAY_LOOKUP_MP_INGAME,
  [LEVEL_ID_MP_ORXON] OVERLAY_LOOKUP_MP_INGAME,
  [LEVEL_ID_MP_VALIX] OVERLAY_LOOKUP_MP_INGAME,
  [49] = -1,
  [LEVEL_ID_MP_TORVAL] OVERLAY_LOOKUP_MP_INGAME,
  [LEVEL_ID_MP_STYGIA] OVERLAY_LOOKUP_MP_INGAME,
  [52] = -1,
  [LEVEL_ID_MP_MARAXUS] OVERLAY_LOOKUP_MP_INGAME,
  [LEVEL_ID_MP_GHOST_STATION] OVERLAY_LOOKUP_MP_INGAME,
  [55] = -1,
  [56] = -1,
  [57] = -1,
  [58] = -1,
  [59] = -1,
  [60] = -1,
  [LEVEL_ID_MP_SPLITSCREEN_BATTLEDOME] OVERLAY_LOOKUP_MP_INGAME,
  [LEVEL_ID_MP_SPLITSCREEN_CATACROM] OVERLAY_LOOKUP_MP_INGAME,
  [63] = -1,
  [LEVEL_ID_MP_SPLITSCREEN_SARATHOS] OVERLAY_LOOKUP_MP_INGAME,
  [LEVEL_ID_MP_SPLITSCREEN_KRONOS] OVERLAY_LOOKUP_MP_INGAME,
  [LEVEL_ID_MP_SPLITSCREEN_SHAAR] OVERLAY_LOOKUP_MP_INGAME,
  [LEVEL_ID_MP_SPLITSCREEN_ORXON] OVERLAY_LOOKUP_MP_INGAME,
  [LEVEL_ID_MP_SPLITSCREEN_VALIX] OVERLAY_LOOKUP_MP_INGAME,
  [69] = -1,
  [LEVEL_ID_MP_SPLITSCREEN_TORVAL] OVERLAY_LOOKUP_MP_INGAME,
  [LEVEL_ID_MP_SPLITSCREEN_STYGIA] OVERLAY_LOOKUP_MP_INGAME,
  [72] = -1,
  [LEVEL_ID_MP_SPLITSCREEN_MARAXUS] OVERLAY_LOOKUP_MP_INGAME,
  [LEVEL_ID_MP_SPLITSCREEN_GHOST_STATION] OVERLAY_LOOKUP_MP_INGAME
};

//--------------------------------------------------------
void* GetOverlayAddress(void** lookup)
{
  if (!lookup) return 0;

  int gameLevel = PEEK_U32(UNDERLAY_GAME_LEVEL);

  // unsupported level
  if (gameLevel < 0 || gameLevel >= LEVEL_ID_COUNT) return 0;
  int lookupIdx = LevelToLookupIndexId[gameLevel];
  if (lookupIdx < 0 || lookupIdx >= OVERLAY_LOOKUP_COUNT) return 0;

  return lookup[lookupIdx];
}
